---
openapi: 3.0.1
info:
  title: p6-gateway
  description: p6 gateway service
  version: "1.0"
servers:
  - url: http://p6-gateway:8080/
paths:
  /v1/deployment:
    post:
      operationId: deployment
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        200:
          description: The token definition.
          headers:
            Deployment-Id:
              style: simple
              schema:
                type: string
  /v1/process/start/{processId}/{processVersion}:
    post:
      operationId: startProcess
      parameters:
        - name: processId
          in: path
          description: Process id
          required: true
          schema:
            type: string
        - name: processVersion
          in: path
          description: Process version
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        200:
          description: The token definition.
          headers:
            Process-Instance-Id:
              style: simple
              schema:
                type: string
